- name: Configuring catlouge
  hosts: catlouge
  become: yes
  tasks:
  - name: Disable the existing node js
    ansible.builtin.command: dnf module enable nodejs:20 -y
      
  - name: install the nodejs:20
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Ensure a system user for the web service exists
    ansible.builtin.user:
      name: roboshop
      comment: "roboshop system user"
      system: yes
      shell: /sbin/nologin
      state: present
      home: /app

  - name: delete the /app folder if already exists
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create a /app directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory


  - name: delete the application binary if alredy exits
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent  
      

  - name: Download application binary
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
      

  - name: unzip the /tmp/catalogue.zip file
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies 
    community.general.npm:
      path: /app

  - name: copy a service file
    ansible.builtin.template:
      src : catalogue.service
      dest: /etc/systemd/system/catalogue.service
      
  
  - name: Setup(copying) the MongoDB repo file
    ansible.builtin.template:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
      

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present


  - name: check products loades or not
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalouge_output

  - name: print the catalouge output
    ansible.builtin.debug:
      msg: "{{ catalouge_output }}"

  - name: load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalouge_output.stdout | int < 0

  - name: start and eneble the catalouge
    ansible.builtin.service:
      name: catalogue
      enabled: yes
      state: restarted




    