[mongodb]
mongodb-dev.ngandham.online

[catlouge]
catalouge-dev.ngandham.online

[redis]
redis-dev.ngandham.online

[cart]
cart-dev.ngandham.online

[user]
user-dev.ngandham.online

[mysql]
mysql-dev.ngandham.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.ngandham.online
REDIS_HOST=redis-dev.ngandham.online
USER_HOST=user-dev.ngandham.online
CATALOUGE_HOST=catalouge-dev.ngandham.online